# Generated by Django 4.2 on 2023-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('learner', 'learner'), ('tutor', 'tutor'), ('moderator', 'moderator')], default='learner', max_length=100),
        ),
    ]
