# Generated by Django 4.2 on 2023-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_score_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
