# Generated by Django 4.2 on 2023-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseries',
            name='subjects',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
