# Generated by Django 4.2 on 2023-11-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_articleseries_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseries',
            name='series_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
