# Generated by Django 4.2.4 on 2023-11-15 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wistify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="first_name", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.FloatField()),
                ("review", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wistify.learner",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wistify.tutor"
                    ),
                ),
            ],
        ),
    ]
